services:
  vueapp:
    image: nginx:stable-alpine
    container_name: gwx-trade
    ports:
      - "8082:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
